---
version: '3'

tasks:

  server:
    desc: Runs a local HTTP server
    cmds:
      - hugo server
    silent: true
    dir: src

  lint:
    desc: Runs pre-commit hooks
    cmds:
      - pre-commit run -a
    silent: true

  clean:
    desc: Removes generated files
    cmds:
      - rm -Rf src/public
    silent: true
